/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int chat_say_radius_cm();
int chat_max_len();
int chat_in_range(int, int);
int chat_msg_len_ok(int);

int chat_say_radius_cm(void) {
    return 4000;
}

int chat_max_len(void) {
    return 200;
}

int chat_in_range(int distance_cm __attribute__((unused)), int radius_cm __attribute__((unused))) {
    return (distance_cm <= radius_cm);
}

int chat_msg_len_ok(int len __attribute__((unused))) {
    if ((len <= 0)) {
    return 0;
    } else {
    return (len <= chat_max_len());
    }
}

