/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int board_count();
int board_speedster();
int board_tank();
int board_glider();
int board_is_valid(int);
int board_accel_x100(int);
int board_friction_x1000(int);
int board_max_speed_x100(int);
int board_gravity_x1000(int);

int board_count(void) {
    return 3;
}

int board_speedster(void) {
    return 1;
}

int board_tank(void) {
    return 2;
}

int board_glider(void) {
    return 3;
}

int board_is_valid(int board_type __attribute__((unused))) {
    if ((board_type < board_speedster())) {
    return 0;
    } else {
    return (board_type <= board_count());
    }
}

int board_accel_x100(int board_type __attribute__((unused))) {
    if ((board_type == board_speedster())) {
    return 1600;
    } else {
    if ((board_type == board_tank())) {
    return 2400;
    } else {
    if ((board_type == board_glider())) {
    return 1000;
    } else {
    return 0;
    }
    }
    }
}

int board_friction_x1000(int board_type __attribute__((unused))) {
    if ((board_type == board_speedster())) {
    return 900;
    } else {
    if ((board_type == board_tank())) {
    return 600;
    } else {
    if ((board_type == board_glider())) {
    return 850;
    } else {
    return 0;
    }
    }
    }
}

int board_max_speed_x100(int board_type __attribute__((unused))) {
    if ((board_type == board_speedster())) {
    return 3500;
    } else {
    if ((board_type == board_tank())) {
    return 1200;
    } else {
    if ((board_type == board_glider())) {
    return 2000;
    } else {
    return 0;
    }
    }
    }
}

int board_gravity_x1000(int board_type __attribute__((unused))) {
    if ((board_type == board_speedster())) {
    return 700;
    } else {
    if ((board_type == board_tank())) {
    return 1000;
    } else {
    if ((board_type == board_glider())) {
    return 300;
    } else {
    return 1000;
    }
    }
    }
}

