/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int material_paper();
int material_wood();
int material_metal();
int item_drop_scrap_id();
int item_drop_shotgun_id();
int item_drop_food_base();
int item_drop_food_count();
int on_papercraft_item_for_object_destroyed(int, int);

int material_paper(void) {
    return 0;
}

int material_wood(void) {
    return 1;
}

int material_metal(void) {
    return 3;
}

int item_drop_scrap_id(void) {
    return 1;
}

int item_drop_shotgun_id(void) {
    return 5;
}

int item_drop_food_base(void) {
    return 8;
}

int item_drop_food_count(void) {
    return 17;
}

int on_papercraft_item_for_object_destroyed(int material __attribute__((unused)), int object_index __attribute__((unused))) {
    if ((material == material_paper())) {
    return item_drop_scrap_id();
    } else {
    if ((material == material_metal())) {
    return item_drop_shotgun_id();
    } else {
    if ((material == material_wood())) {
    return (item_drop_food_base() + (object_index % item_drop_food_count()));
    } else {
    return 0;
    }
    }
    }
}

