/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int party_max_size();
int party_max_members();
int party_ok();
int party_err_not_leader();
int party_err_full();
int party_err_already_in_party();
int party_err_not_in_party();
int party_err_cannot_kick_self();
int party_full(int);
int party_can_invite(int, int, int);
int party_can_kick(int, int, int);
int party_in_range(int, int);
int party_xp_share(int, int);

int party_max_size(void) {
    return 6;
}

int party_max_members(void) {
    return 5;
}

int party_ok(void) {
    return 0;
}

int party_err_not_leader(void) {
    return 1;
}

int party_err_full(void) {
    return 2;
}

int party_err_already_in_party(void) {
    return 3;
}

int party_err_not_in_party(void) {
    return 4;
}

int party_err_cannot_kick_self(void) {
    return 5;
}

int party_full(int size __attribute__((unused))) {
    return (size >= party_max_size());
}

int party_can_invite(int is_caller_leader __attribute__((unused)), int size __attribute__((unused)), int is_target_already_in_party __attribute__((unused))) {
    if ((!(is_caller_leader))) {
    return party_err_not_leader();
    } else {
    if (party_full(size)) {
    return party_err_full();
    } else {
    if (is_target_already_in_party) {
    return party_err_already_in_party();
    } else {
    return party_ok();
    }
    }
    }
}

int party_can_kick(int is_caller_leader __attribute__((unused)), int is_target_self __attribute__((unused)), int is_target_in_party __attribute__((unused))) {
    if ((!(is_caller_leader))) {
    return party_err_not_leader();
    } else {
    if (is_target_self) {
    return party_err_cannot_kick_self();
    } else {
    if ((!(is_target_in_party))) {
    return party_err_not_in_party();
    } else {
    return party_ok();
    }
    }
    }
}

int party_in_range(int distance_cm __attribute__((unused)), int range_limit_cm __attribute__((unused))) {
    return (distance_cm <= range_limit_cm);
}

int party_xp_share(int total_xp __attribute__((unused)), int in_range_count __attribute__((unused))) {
    if ((in_range_count <= 0)) {
    return 0;
    } else {
    return (total_xp / in_range_count);
    }
}

