/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int event_dispatched();
int event_resolved();
int callsign_none();
int callsign_responding_quiet();
int callsign_responding_code_red();
int callsign_resolved();
int walkie_callsign_for_event(int, int);

int event_dispatched(void) {
    return 1;
}

int event_resolved(void) {
    return 2;
}

int callsign_none(void) {
    return 0;
}

int callsign_responding_quiet(void) {
    return 1;
}

int callsign_responding_code_red(void) {
    return 2;
}

int callsign_resolved(void) {
    return 3;
}

int walkie_callsign_for_event(int event __attribute__((unused)), int witness_state __attribute__((unused))) {
    if ((event == event_resolved())) {
    return callsign_resolved();
    } else {
    if ((event == event_dispatched())) {
    if ((witness_state == 5)) {
    return callsign_responding_code_red();
    } else {
    if ((witness_state == 3)) {
    return callsign_responding_quiet();
    } else {
    return callsign_none();
    }
    }
    } else {
    return callsign_none();
    }
    }
}

